### ISSUE TITLE
Objetivo Geral

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-EmaFlix#3]
Foram declarados dois objetivos: (1) organizar e (2) facilitar. qual é o objetivo?

"Organizar e facilitar o acesso às obras cinematográficas criadas pelos alunos do IFB​, agregando as produções em uma unica plataforma."

**Comment by DaniloNavesS** [comment]
O objetivo geral foi refatorado.
