### ISSUE TITLE
Objetivos especificos

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-EmaFlix#4]
foram apresentadas características do produto e não objetivos que se quer atingir, a partir do produto.

Criar uma espaço para críticas especializadas, dando mais visibilidade para especialistas no assunto.

Organizar as produções de acordo com gênero, sub gênero e classificação indicativa.

Facilitar a entrega dos filmes para a comunidade.

**Comment by DaniloNavesS** [comment]
Fechada.
