### ISSUE TITLE
Tecnologias a Serem Utilizadas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-EmaFlix#5]
detalhem mais, por exemplo, que versões android e ios.

Plataforma: Aplicação web, Android, IOS Linguagens de programação: Flutter, Java

**Comment by marsicanogeorge** [comment]
quais ferramentas utilizarão em cada parte do projeto (backend, frontend, testes...)?

**Comment by DaniloNavesS** [comment]
Foram trabalhadas as questões citadas acima.
